In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import pandas as pd

In [2]:
torch.manual_seed(1)

x_data = [[0,0],[0,1],[1,0],[1,1]]
t_data_and= [[0],[0],[0],[1]]
t_data_or= [[0],[1],[1],[1]]
t_data_nand= [[1],[1],[1],[0]]
t_data_xor= [[0],[1],[1],[0]]

x_train=torch.FloatTensor(x_data)
t_train_and=torch.FloatTensor(t_data_and)
t_train_or=torch.FloatTensor(t_data_or)
t_train_nand=torch.FloatTensor(t_data_nand)
t_train_xor=torch.FloatTensor(t_data_xor)



In [13]:
def logic_func(x_train,t_train):
    model=nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid())

    optimizer=optim.SGD(model.parameters(), lr=0.1)
    epochs=1001

    for epoch in range(epochs):
        h=model(x_train)
        cost=F.binary_cross_entropy(h, t_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        if epoch%100==0:
            print(epoch, cost.item())

    result=model(x_train)
    return result

In [14]:
result_or=logic_func(x_train, t_train_or)
result_or=(result_or>=torch.FloatTensor([0.5])).float()
result_or

0 0.7152550220489502
100 0.34177976846694946
200 0.2663002908229828
300 0.21686872839927673
400 0.182096928358078
500 0.15643197298049927
600 0.1367729753255844
700 0.12127205729484558
800 0.1087634488940239
900 0.09847612679004669
1000 0.08988014608621597


tensor([[0.],
        [1.],
        [1.],
        [1.]])

In [16]:
result_nand=logic_func(x_train, t_train_nand)
result_nand=(result_nand>=torch.FloatTensor([0.5])).float()
result_nand

0 0.6943425536155701
100 0.4643380045890808
200 0.36436447501182556
300 0.30256763100624084
400 0.260067880153656
500 0.22866642475128174
600 0.20430675148963928
700 0.18474730849266052
800 0.16863781213760376
900 0.15510861575603485
1000 0.14356935024261475


tensor([[1.],
        [1.],
        [1.],
        [0.]])

In [17]:
input=[]
for i in range(result_or.size(0)):
    input.append([result_or[i][0].item(), result_nand[i][0].item()])
    
x_train=torch.FloatTensor(input)
xor_result=logic_func(x_train, t_train_xor)
xor_result=(xor_result>=torch.FloatTensor([0.5])).float()
xor_result

0 0.612721860408783
100 0.5063209533691406
200 0.4261166751384735
300 0.36447468400001526
400 0.31626197695732117
500 0.2779186964035034
600 0.2469417005777359
700 0.22154879570007324
800 0.20045380294322968
900 0.1827157437801361
1000 0.16763582825660706


tensor([[0.],
        [1.],
        [1.],
        [0.]])