In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
model=nn.Linear(1,1) # input_dim=1, output_dim=1  y=wx+b
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [4]:
optimizer=optim.SGD(model.parameters(), lr=0.01)
epochs=2001

for epoch in range(epochs):
    h=model(x_data)
    cost=F.mse_loss(h,t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('epoch:',epoch, 'cost:',cost.item())


epoch: 0 cost: 39.16685104370117
epoch: 100 cost: 0.08463062345981598
epoch: 200 cost: 0.04298952594399452
epoch: 300 cost: 0.021837208420038223
epoch: 400 cost: 0.01109258271753788
epoch: 500 cost: 0.00563468411564827
epoch: 600 cost: 0.0028622171375900507
epoch: 700 cost: 0.0014539161929860711
epoch: 800 cost: 0.0007385412463918328
epoch: 900 cost: 0.00037515218718908727
epoch: 1000 cost: 0.00019056595920119435
epoch: 1100 cost: 9.680409129941836e-05
epoch: 1200 cost: 4.91717473778408e-05
epoch: 1300 cost: 2.497919740562793e-05
epoch: 1400 cost: 1.2689983122982085e-05
epoch: 1500 cost: 6.447205578297144e-06
epoch: 1600 cost: 3.276181814726442e-06
epoch: 1700 cost: 1.6654261116855196e-06
epoch: 1800 cost: 8.460160643153358e-07
epoch: 1900 cost: 4.302897309571563e-07
epoch: 2000 cost: 2.1860606125301274e-07


In [7]:
import pandas as pd
df=pd.read_csv('data-01-test-score.csv')
data=np.array(df.values)
x_data=data[:,:3].reshape(-1, 3)
t_data=data[:,-1].reshape(-1, 1)
print(x_data)
print(t_data)

x_data3=torch.from_numpy(x_data).float()
t_data3=torch.from_numpy(t_data).float()
print(x_data3)
print(t_data3)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]
tensor([[ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  

In [8]:
torch.manual_seed(1)
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [11]:
optimizer=optim.SGD(model.parameters(), lr=1e-6)

epochs = 20001
for epoch in range(epochs):
    y = model(x_data3) # y=wx+b를 알아서 만든다.
    cost = F.mse_loss(y, t_data3)

    optimizer.zero_grad()
    cost.backward() # 기울기 계산
    optimizer.step()

    if epoch%400==0:
        print('epoch:', epoch, 'cost:', cost.item())
        print("Parameters:", list(model.parameters()))
        

epoch: 0 cost: 9.430891036987305
Parameters: [Parameter containing:
tensor([[0.7282, 0.4302, 0.8600]], requires_grad=True), Parameter containing:
tensor([0.2783], requires_grad=True)]
epoch: 400 cost: 9.361556053161621
Parameters: [Parameter containing:
tensor([[0.7243, 0.4305, 0.8635]], requires_grad=True), Parameter containing:
tensor([0.2782], requires_grad=True)]
epoch: 800 cost: 9.29389476776123
Parameters: [Parameter containing:
tensor([[0.7204, 0.4308, 0.8670]], requires_grad=True), Parameter containing:
tensor([0.2782], requires_grad=True)]
epoch: 1200 cost: 9.227849006652832
Parameters: [Parameter containing:
tensor([[0.7166, 0.4312, 0.8704]], requires_grad=True), Parameter containing:
tensor([0.2782], requires_grad=True)]
epoch: 1600 cost: 9.163348197937012
Parameters: [Parameter containing:
tensor([[0.7128, 0.4315, 0.8737]], requires_grad=True), Parameter containing:
tensor([0.2781], requires_grad=True)]
epoch: 2000 cost: 9.10043716430664
Parameters: [Parameter containing:
t

## Class 사용

In [ ]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [ ]:
class LinearRegressionModel(nn.Module):
    def __init__(self): # 모델생성
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = LinearRegressionModel()
print(list(model.parameters()))
optimizer = optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
epochs = 2001
for epoch in range(epochs):
    y = model(x_data)
    cost = F.mse_loss(y, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 ==0:
        print(epoch, cost.item(), list(model.parameters()))


0 39.16685104370117 [Parameter containing:
tensor([[0.9284]], requires_grad=True), Parameter containing:
tensor([-0.3235], requires_grad=True)]
100 0.08463062345981598 [Parameter containing:
tensor([[2.1882]], requires_grad=True), Parameter containing:
tensor([0.3204], requires_grad=True)]
200 0.04298952594399452 [Parameter containing:
tensor([[2.1342]], requires_grad=True), Parameter containing:
tensor([0.5157], requires_grad=True)]
300 0.021837208420038223 [Parameter containing:
tensor([[2.0956]], requires_grad=True), Parameter containing:
tensor([0.6548], requires_grad=True)]
400 0.01109258271753788 [Parameter containing:
tensor([[2.0681]], requires_grad=True), Parameter containing:
tensor([0.7540], requires_grad=True)]
500 0.00563468411564827 [Parameter containing:
tensor([[2.0486]], requires_grad=True), Parameter containing:
tensor([0.8246], requires_grad=True)]
600 0.0028622171375900507 [Parameter containing:
tensor([[2.0346]], requires_grad=True), Parameter containing:
tensor([0

In [58]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self): # 모델생성
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)


In [61]:
model2 = MultiLinearRegressionModel()
print(list(model2.parameters()))
optimizer = optim.SGD(model2.parameters(), lr=0.00001)

[Parameter containing:
tensor([[ 0.2109, -0.2250, -0.0421]], requires_grad=True), Parameter containing:
tensor([-0.0520], requires_grad=True)]


In [62]:
epochs = 200001
for epoch in range(epochs):
    y = model2(x_data3)
    cost = F.mse_loss(y, t_data3)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400 ==0:
        print(epoch, cost.item(), list(model2.parameters()))


0 28533.09375 [Parameter containing:
tensor([[0.4815, 0.0464, 0.2367]], requires_grad=True), Parameter containing:
tensor([-0.0486], requires_grad=True)]
400 12.266325950622559 [Parameter containing:
tensor([[0.8434, 0.4564, 0.7264]], requires_grad=True), Parameter containing:
tensor([-0.0436], requires_grad=True)]
800 10.967647552490234 [Parameter containing:
tensor([[0.7941, 0.4519, 0.7787]], requires_grad=True), Parameter containing:
tensor([-0.0438], requires_grad=True)]
1200 9.96887493133545 [Parameter containing:
tensor([[0.7498, 0.4498, 0.8237]], requires_grad=True), Parameter containing:
tensor([-0.0441], requires_grad=True)]
1600 9.196438789367676 [Parameter containing:
tensor([[0.7101, 0.4497, 0.8625]], requires_grad=True), Parameter containing:
tensor([-0.0444], requires_grad=True)]
2000 8.595927238464355 [Parameter containing:
tensor([[0.6743, 0.4511, 0.8959]], requires_grad=True), Parameter containing:
tensor([-0.0448], requires_grad=True)]
2400 8.126696586608887 [Paramete

In [65]:
x = torch.FloatTensor([[75,80,85],[80,75,85],[75,85,80]])
model2(x)

tensor([[164.9958],
        [164.0335],
        [162.0641]], grad_fn=<AddmmBackward0>)