In [41]:
import numpy as np
import matplotlib.pyplot as plt

In [42]:
x_data1=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [43]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.09097465]
 [0.23984939]]
[0.14296597]


In [44]:
# 제곱 손실
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [45]:
# 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx] =(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    
    return grad

In [46]:
# 예측
def predict(x):
    y=np.dot(x, w)+b

In [47]:
# 훈련
learning_rate=1e-4
f=lambda x: loss_func(x_data1, t_data1)
print('init error value=',loss_func(x_data1, t_data1), 'init w=',w, 'init b=',b)

for step in range(2001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 100 == 0:
        print('step=',step, 'error value=',loss_func(x_data1,t_data1), 'w=',w, 'b=', b)

init error value= 37.20968758104573 init w= [[0.09097465]
 [0.23984939]] init b= [0.14296597]
step= 0 error value= 36.76798403735743 w= [[0.09501715]
 [0.24501683]] b= [0.14408435]
step= 100 error value= 11.150876568319323 w= [[0.39864695]
 [0.63274265]] b= [0.22768801]
step= 200 error value= 3.3986665201204316 w= [[0.56608559]
 [0.84584176]] b= [0.27307755]
step= 300 error value= 1.0525650124712258 w= [[0.65860379]
 [0.96287946]] b= [0.2974479]
step= 400 error value= 0.34241258606541486 w= [[0.7099066 ]
 [1.02707451]] b= [0.31025801]
step= 500 error value= 0.12731880778400245 w= [[0.73853517]
 [1.06220158]] b= [0.31671122]
step= 600 error value= 0.062037599334172855 w= [[0.75468901]
 [1.08133909]] b= [0.31966989]
step= 700 error value= 0.042093410870286396 w= [[0.76397888]
 [1.09168149]] b= [0.32070858]
step= 800 error value= 0.03587055613997507 w= [[0.76949124]
 [1.09718644]] b= [0.32069346]
step= 900 error value= 0.03380162441426761 w= [[0.77292398]
 [1.10003106]] b= [0.320101]
step

In [48]:
import pandas as pd
df=pd.read_csv('data/data-01-test-score.csv')
data=np.array(df.values)
x_data = data[:, :3].reshape(-1,3)
t_data = data[:, :-1].reshape(-1,1)
print(x_data)
print(t_data)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[ 93]
 [ 88]
 [ 93]
 [ 89]
 [ 91]
 [ 90]
 [ 96]
 [ 98]
 [100]
 [ 73]
 [ 66]
 [ 70]
 [ 53]
 [ 46]
 [ 55]
 [ 69]
 [ 74]
 [ 77]
 [ 47]
 [ 56]
 [ 60]
 [ 87]
 [ 79]
 [ 90]
 [ 79]
 [ 70]
 [ 88]
 [ 69]
 [ 70]
 [ 73]
 [ 70]
 [ 65]
 [ 74]
 [ 93]
 [ 95]
 [ 91]
 [ 79]
 [ 80]
 [ 73]
 [ 70]
 [ 73]
 [ 78]
 [ 93]
 [ 89]
 [ 96]
 [ 78]
 [ 75]
 [ 68]
 [ 81]
 [ 90]
 [ 93]
 [ 88]
 [ 92]
 [ 86]
 [ 78]
 [ 83]
 [ 77]
 [ 82]
 [ 86]
 [ 90]
 [ 86]
 [ 82]
 [ 89]
 [ 78]
 [ 83]
 [ 85]
 [ 76]
 [ 83]
 [ 71]
 [ 96]
 [ 93]
 [ 95]]


In [49]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.52838703]
 [0.51335551]]
[0.89772216]


In [50]:
# 제곱 손실
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [51]:
# 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx] =(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    
    return grad

In [52]:
# 예측
def predict(x):
    y = np.dot(x, w) + b
    return y

In [53]:
# 훈련
learning_rate=1e-4
f=lambda x: loss_func(x_data1, t_data1)
print('init error value=',loss_func(x_data1, t_data1), 'init w=',w, 'init b=',b)

for step in range(2001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 100 == 0:
        print('step=',step, 'error value=',loss_func(x_data1,t_data1), 'w=',w, 'b=', b)

init error value= 7.906306307046478 init w= [[0.52838703]
 [0.51335551]] init b= [0.89772216]
step= 0 error value= 7.81409079880064 w= [[0.53024855]
 [0.51570977]] b= [0.8982119]
step= 100 error value= 2.4654694260858676 w= [[0.67042563]
 [0.69219027]] b= [0.93429004]
step= 200 error value= 0.8460978136974605 w= [[0.74837291]
 [0.78888881]] b= [0.95291716]
step= 300 error value= 0.3552486266399769 w= [[0.79208422]
 [0.84170082]] b= [0.96194939]
step= 400 error value= 0.20591210976022972 w= [[0.81695897]
 [0.87037238]] b= [0.96570834]
step= 500 error value= 0.15992931093428917 w= [[0.8314684 ]
 [0.88576581]] b= [0.96657132]
step= 600 error value= 0.14522989836499664 w= [[0.84027253]
 [0.89385645]] b= [0.96584607]
step= 700 error value= 0.14000407902039808 w= [[0.84593488]
 [0.89793135]] b= [0.96425196]


step= 800 error value= 0.13765164831847793 w= [[0.84986564]
 [0.89979869]] b= [0.96218469]
step= 900 error value= 0.13617510878576117 w= [[0.85284058]
 [0.90045317]] b= [0.95986192]
step= 1000 error value= 0.1349698609329146 w= [[0.85528645]
 [0.90044194]] b= [0.95740337]
step= 1100 error value= 0.13385285001605932 w= [[0.85743802]
 [0.90006601]] b= [0.95487487]
step= 1200 error value= 0.13276860692526665 w= [[0.85942447]
 [0.89949093]] b= [0.95231262]
step= 1300 error value= 0.13170028344078982 w= [[0.86131684]
 [0.89880779]] b= [0.9497365]
step= 1400 error value= 0.1306427252646954 w= [[0.86315426]
 [0.89806667]] b= [0.94715746]
step= 1500 error value= 0.12959432072315064 w= [[0.86495825]
 [0.89729513]] b= [0.94458147]
step= 1600 error value= 0.12855453249772875 w= [[0.86674065]
 [0.89650831]] b= [0.94201181]
step= 1700 error value= 0.12752314982245092 w= [[0.86850801]
 [0.89571456]] b= [0.93945027]
step= 1800 error value= 0.12650006170763964 w= [[0.87026393]
 [0.89491843]] b= [0.936

In [59]:
predict(np.array([[75,80,85]]))


ValueError: shapes (1,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)