In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x_data1=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [5]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.66275067]
 [0.51997971]]
[0.56214702]


In [6]:
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [7]:
def numerical_derivative(f, x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]

        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [8]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [13]:
learning_rate=1e-4
f=lambda x:loss_func(x_data1, t_data1)
print('init error value=', loss_func(x_data1, t_data1), 'init w=',w, 'init b=',b)

for step in range(200001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step %100==0:
        print('step=', step, 'error value=',loss_func(x_data1, t_data1), 'w=',w ,'b=',b)

init error value= 6.708253403805057 init w= [[0.66796582]
 [0.52660792]] init b= [0.56355165]
step= 0 error value= 6.629170720356387 w= [[0.66968366]
 [0.52879099]] b= [0.5640141]
step= 100 error value= 2.0425179887307268 w= [[0.79889198]
 [0.692508  ]] b= [0.5983143]
step= 200 error value= 0.654249183165207 w= [[0.87047206]
 [0.78233823]] b= [0.61644963]
step= 300 error value= 0.2338501214439578 w= [[0.91034881]
 [0.83152424]] b= [0.62569561]
step= 400 error value= 0.10634276309310205 w= [[0.93278355]
 [0.8583528 ]] b= [0.63005451]
step= 500 error value= 0.06747090291776602 w= [[0.94562144]
 [0.87288343]] b= [0.63172793]
step= 600 error value= 0.055423984475586816 w= [[0.95317809]
 [0.88064989]] b= [0.63192699]
step= 700 error value= 0.05149719345122024 w= [[0.95782756]
 [0.88469629]] b= [0.63131789]
step= 800 error value= 0.05003008378734357 w= [[0.96087579]
 [0.88669719]] b= [0.63026713]
step= 900 error value= 0.04930964067868645 w= [[0.96304122]
 [0.88757377]] b= [0.62897628]
step=

In [15]:
predict(np.array([[7,8]]))
predict(np.array([[11,12]]))

array([[22.9996406]])

In [41]:
import pandas as pd
df=pd.read_csv('data-01-test-score.csv')
data=np.array(df.values)
x_data=data[:,:3].reshape(-1, 3)
t_data=data[:,-1].reshape(-1, 1)
print(x_data)
print(t_data)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]


In [30]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.18296785]
 [0.18869852]
 [0.37175358]]
[0.41947597]


In [32]:
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [33]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)

        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    return grad

In [34]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [40]:
learning_rate=1e-6

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data), "Initial w=", w, "b=",b)

for step in range(20001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=", w, "b=",b)

Initial error value= 6.391399713096497 Initial w= [[0.3669543 ]
 [0.53174854]
 [1.11060156]] b= [0.40869382]
step= 0 error value= 6.39139933793884 w= [[0.36695383]
 [0.5317487 ]
 [1.11060187]] b= [0.40869364]
step= 400 error value= 6.391250725103714 w= [[0.36676553]
 [0.53181358]
 [1.11072253]] b= [0.40862139]
step= 800 error value= 6.391104963278188 w= [[0.36657917]
 [0.53187812]
 [1.11084164]] b= [0.40854912]
step= 1200 error value= 6.390961990303057 w= [[0.36639473]
 [0.53194232]
 [1.11095921]] b= [0.40847684]
step= 1600 error value= 6.390821745441958 w= [[0.36621218]
 [0.53200619]
 [1.11107527]] b= [0.40840455]
step= 2000 error value= 6.390684169346461 w= [[0.36603151]
 [0.53206972]
 [1.11118984]] b= [0.40833224]
step= 2400 error value= 6.390549204022445 w= [[0.3658527 ]
 [0.5321329 ]
 [1.11130293]] b= [0.40825992]
step= 2800 error value= 6.390416792797073 w= [[0.36567573]
 [0.53219574]
 [1.11141458]] b= [0.40818759]
step= 3200 error value= 6.390286880286692 w= [[0.36550057]
 [0.53

In [44]:
print(predict(np.array([[75,80,85]])))
print(predict(np.array([[85,80,75]])))
print(predict(np.array([[75,85,80]])))


[[164.91971738]]
[[157.36442112]]
[[162.017076]]
