In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x_data1=np.array([1,2,3,4,5]).reshape(5,1)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [13]:
x_data2=np.array([9,14,21,27,32,37]).reshape(6,1)
t_data2=np.array([74,81,86,90,88,92]).reshape(6,1)

In [19]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w, b)

[[0.18755547]] [0.60515509]


In [15]:
def loss_func1(x, t):
    y=np.dot(x, w)+ b

    return (np.sum((t-y)**2))/(len(x))

In [16]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [17]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [23]:
cost_list=[]
learning_rate=1e-4

f=lambda x: loss_func1(x_data2, t_data2)

print("Initial error value:", loss_func1(x_data2, t_data2), 'Initial w=',w, 'Initial b=',b )

for step in range(200001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 100==0:
        print('step:', step, 'error value:',loss_func1(x_data2, t_data2), 'w:',w, 'b:',b)


Initial error value: 4.634883749828122 Initial w= [[0.5802486]] Initial b= [71.62746704]
step: 0 error value: 4.634883749826393 w: [[0.5802486]] b: [71.62746705]
step: 100 error value: 4.634883749654535 w: [[0.58024855]] b: [71.62746836]
step: 200 error value: 4.63488374948369 w: [[0.58024851]] b: [71.62746966]
step: 300 error value: 4.634883749313873 w: [[0.58024846]] b: [71.62747097]
step: 400 error value: 4.634883749145053 w: [[0.58024841]] b: [71.62747227]
step: 500 error value: 4.6348837489772405 w: [[0.58024836]] b: [71.62747356]
step: 600 error value: 4.634883748810426 w: [[0.58024832]] b: [71.62747485]
step: 700 error value: 4.634883748644593 w: [[0.58024827]] b: [71.62747614]
step: 800 error value: 4.634883748479783 w: [[0.58024822]] b: [71.62747742]
step: 900 error value: 4.634883748315915 w: [[0.58024818]] b: [71.6274787]
step: 1000 error value: 4.6348837481530305 w: [[0.58024813]] b: [71.62747998]
step: 1100 error value: 4.634883747991137 w: [[0.58024808]] b: [71.62748125]


In [30]:
predict(np.array([48]).reshape(1,1))

array([[99.47907061]])