In [21]:
import numpy as np
import matplotlib.pyplot as plt

In [22]:
x_data1=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [23]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.28319713]
 [0.41631486]]
[0.23967707]


In [24]:
# 제곱 손실
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [25]:
# 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx] =(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    
    return grad

In [26]:
# 예측
def predict(x):
    y=np.dot(x, w)+b

In [27]:
# 훈련
learning_rate=1e-4
f=lambda x: loss_func(x_data1, t_data1)
print('init error value=',loss_func(x_data1, t_data1), 'init w=',w, 'init b=',b)

for step in range(2001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 100 == 0:
        print('step=',step, 'error value=',loss_func(x_data1,t_data1), 'w=',w, 'b=', b)

init error value= 21.406571347551655 init w= [[0.28319713]
 [0.41631486]] init b= [0.23967707]
step= 0 error value= 21.152672999231864 w= [[0.28626461]
 [0.42023143]] b= [0.24052119]
step= 100 error value= 6.427481415278841 w= [[0.51672549]
 [0.71407201]] b= [0.30352754]
step= 200 error value= 1.971263508950368 w= [[0.64393009]
 [0.8755174 ]] b= [0.33756285]
step= 300 error value= 0.6225490153890247 w= [[0.7143317 ]
 [0.96413297]] b= [0.35566369]
step= 400 error value= 0.21420159409246842 w= [[0.75348424]
 [1.01268564]] b= [0.36500147]
step= 500 error value= 0.09042228110571185 w= [[0.77544497]
 [1.03920048]] b= [0.36952119]
step= 600 error value= 0.052758820237995344 w= [[0.78794678]
 [1.05359308]] b= [0.37139298]
step= 700 error value= 0.04115708207585418 w= [[0.79524354]
 [1.06131803]] b= [0.3718106]
step= 800 error value= 0.037443818291012516 w= [[0.79967532]
 [1.06537586]] b= [0.37143074]
step= 900 error value= 0.036119471600653985 w= [[0.8025294 ]
 [1.06741718]] b= [0.37061465]
s

step= 1500 error value= 0.03398707945574152 w= [[0.8103168 ]
 [1.06782827]] b= [0.36323333]
step= 1600 error value= 0.033714167586716234 w= [[0.81124987]
 [1.06745134]] b= [0.36192308]
step= 1700 error value= 0.0334436139770247 w= [[0.81216611]
 [1.06705916]] b= [0.36061442]
step= 1800 error value= 0.03317528271963818 w= [[0.81307146]
 [1.06665933]] b= [0.35930901]
step= 1900 error value= 0.03290912026111999 w= [[0.81396922]
 [1.06625602]] b= [0.35800773]
step= 2000 error value= 0.03264509821461831 w= [[0.8148612 ]
 [1.06585155]] b= [0.35671107]


In [28]:
import pandas as pd
df=pd.read_csv('data/data-01-test-score.csv')
data=np.array(df.values)
x_data = data[:, :3].reshape(-1,3)
t_data = data[:, :-1].reshape(-1,1)
print(x_data)
print(t_data)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[ 93]
 [ 88]
 [ 93]
 [ 89]
 [ 91]
 [ 90]
 [ 96]
 [ 98]
 [100]
 [ 73]
 [ 66]
 [ 70]
 [ 53]
 [ 46]
 [ 55]
 [ 69]
 [ 74]
 [ 77]
 [ 47]
 [ 56]
 [ 60]
 [ 87]
 [ 79]
 [ 90]
 [ 79]
 [ 70]
 [ 88]
 [ 69]
 [ 70]
 [ 73]
 [ 70]
 [ 65]
 [ 74]
 [ 93]
 [ 95]
 [ 91]
 [ 79]
 [ 80]
 [ 73]
 [ 70]
 [ 73]
 [ 78]
 [ 93]
 [ 89]
 [ 96]
 [ 78]
 [ 75]
 [ 68]
 [ 81]
 [ 90]
 [ 93]
 [ 88]
 [ 92]
 [ 86]
 [ 78]
 [ 83]
 [ 77]
 [ 82]
 [ 86]
 [ 90]
 [ 86]
 [ 82]
 [ 89]
 [ 78]
 [ 83]
 [ 85]
 [ 76]
 [ 83]
 [ 71]
 [ 96]
 [ 93]
 [ 95]]


In [29]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.73323889]
 [0.67164879]]
[0.50584147]


In [30]:
# 제곱 손실
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [31]:
# 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx] =(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    
    return grad

In [32]:
# 예측
def predict(x):
    y = np.dot(x, w) + b
    return y

In [33]:
# 훈련
learning_rate=1e-4
f=lambda x: loss_func(x_data1, t_data1)
print('init error value=',loss_func(x_data1, t_data1), 'init w=',w, 'init b=',b)

for step in range(2001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 100 == 0:
        print('step=',step, 'error value=',loss_func(x_data1,t_data1), 'w=',w, 'b=', b)

init error value= 3.293488426925239 init w= [[0.73323889]
 [0.67164879]] init b= [0.50584147]
step= 0 error value= 3.2548742468319887 w= [[0.73444164]
 [0.67317311]] b= [0.5061611]
step= 100 error value= 1.0152596481842155 w= [[0.82496639]
 [0.7874609 ]] b= [0.52977839]
step= 200 error value= 0.3372809612497255 w= [[0.87522224]
 [0.85012047]] b= [0.54210183]
step= 300 error value= 0.1318736225839841 w= [[0.90332431]
 [0.88438019]] b= [0.54821521]
step= 400 error value= 0.06947448541592857 w= [[0.91923775]
 [0.90301799]] b= [0.55091511]
step= 500 error value= 0.05035375647138331 w= [[0.9284444 ]
 [0.91306301]] b= [0.55173992]
step= 600 error value= 0.04433183058367901 w= [[0.93395982]
 [0.91838197]] b= [0.5515359]
step= 700 error value= 0.04227585024252433 w= [[0.93744289]
 [0.92110196]] b= [0.55076856]
step= 800 error value= 0.04142200225617078 w= [[0.93980615]
 [0.92239309]] b= [0.54969397]
step= 900 error value= 0.040933857429426936 w= [[0.94155161]
 [0.92289901]] b= [0.54845298]
ste

In [40]:
predict(np.array([[75,80,85]]))


ValueError: shapes (1,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)