In [32]:
import torch
import torch.nn.functional as F

In [33]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [34]:
z=torch.rand(3,5,requires_grad=True)
y_hat=F.softmax(z, dim=1)
print(z)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.1768, 0.8248, 0.8036, 0.9434, 0.2197],
        [0.4177, 0.4903, 0.5730, 0.1205, 0.1452],
        [0.7720, 0.3828, 0.7442, 0.5285, 0.6642]], requires_grad=True)
tensor([[0.1253, 0.2396, 0.2345, 0.2698, 0.1308],
        [0.2106, 0.2265, 0.2460, 0.1565, 0.1604],
        [0.2308, 0.1564, 0.2245, 0.1810, 0.2073]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [35]:
y=torch.randint(5,(3,)).long()
print(y)
print(y_hat)
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot)
print(y.unsqueeze(1))
y_one_hot.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot)


tensor([3, 0, 4])
tensor([[0.1253, 0.2396, 0.2345, 0.2698, 0.1308],
        [0.2106, 0.2265, 0.2460, 0.1565, 0.1604],
        [0.2308, 0.1564, 0.2245, 0.1810, 0.2073]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[3],
        [0],
        [4]])
tensor([[0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])


In [36]:
import torch.nn as nn
import torch.optim as optim

In [37]:
torch.manual_seed(1)
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]

x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [38]:
y_one_hot=torch.zeros(8,3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [39]:
w=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True)
print(w)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [40]:
optimizer=optim.SGD([w,b],lr=0.1)
epochs=10001
for epoch in range(epochs):
    y_hat=F.softmax(x_train.matmul(w)+b)
    cost=(y_one_hot* -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch:',epoch, 'cost:',cost.item())

epoch: 0 cost: 1.0986123085021973
epoch: 100 cost: 0.7041996121406555
epoch: 200 cost: 0.6229995489120483


epoch: 300 cost: 0.5657169222831726
epoch: 400 cost: 0.5152913331985474


C:\Users\it\AppData\Local\Temp\ipykernel_1564\4218742925.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y_hat=F.softmax(x_train.matmul(w)+b)


epoch: 500 cost: 0.467661589384079
epoch: 600 cost: 0.4212779700756073
epoch: 700 cost: 0.37540146708488464
epoch: 800 cost: 0.3297656178474426
epoch: 900 cost: 0.2850724160671234
epoch: 1000 cost: 0.24815461039543152
epoch: 1100 cost: 0.23267605900764465
epoch: 1200 cost: 0.22139872610569
epoch: 1300 cost: 0.2111290991306305
epoch: 1400 cost: 0.2017364501953125
epoch: 1500 cost: 0.19311320781707764
epoch: 1600 cost: 0.18516962230205536
epoch: 1700 cost: 0.177829310297966
epoch: 1800 cost: 0.17102722823619843
epoch: 1900 cost: 0.16470743715763092
epoch: 2000 cost: 0.1588211953639984
epoch: 2100 cost: 0.15332652628421783
epoch: 2200 cost: 0.14818623661994934
epoch: 2300 cost: 0.1433679759502411
epoch: 2400 cost: 0.13884282112121582
epoch: 2500 cost: 0.13458563387393951
epoch: 2600 cost: 0.1305735558271408
epoch: 2700 cost: 0.126786470413208
epoch: 2800 cost: 0.12320637702941895
epoch: 2900 cost: 0.11981715261936188
epoch: 3000 cost: 0.1166040301322937
epoch: 3100 cost: 0.113554000854492

In [41]:
y_hat = F.softmax(x_train.matmul(w)+b, dim=1)
print(y_one_hot)
print(y_hat)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])
tensor([[7.9508e-11, 6.5691e-06, 9.9999e-01],
        [1.7811e-04, 1.9474e-02, 9.8035e-01],
        [1.1671e-13, 4.1809e-02, 9.5819e-01],
        [6.1380e-10, 9.6248e-01, 3.7520e-02],
        [7.2622e-02, 9.2453e-01, 2.8516e-03],
        [3.8537e-02, 9.6146e-01, 7.0805e-08],
        [9.1230e-01, 8.7704e-02, 8.1008e-08],
        [9.9212e-01, 7.8797e-03, 5.7660e-11]], grad_fn=<SoftmaxBackward0>)


In [42]:
for y in y_hat:
    print(y.argmax().item())

2
2
2
1
1
1
0
0


In [43]:
model=nn.Linear(4,3) #input_dim, output_dim
optimizer=optim.SGD(model.parameters(), lr=0.1)
epochs=10001

In [44]:
for epoch in range(epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch:',epoch, 'cost:',cost.item())

epoch: 0 cost: 1.6167852878570557
epoch: 100 cost: 0.6588907837867737
epoch: 200 cost: 0.5734435319900513
epoch: 300 cost: 0.5181514620780945
epoch: 400 cost: 0.47326555848121643
epoch: 500 cost: 0.4335159659385681
epoch: 600 cost: 0.3965631425380707
epoch: 700 cost: 0.3609141409397125
epoch: 800 cost: 0.32539206743240356
epoch: 900 cost: 0.2891784608364105
epoch: 1000 cost: 0.25414785742759705
epoch: 1100 cost: 0.23497334122657776
epoch: 1200 cost: 0.2234925627708435
epoch: 1300 cost: 0.21305325627326965
epoch: 1400 cost: 0.20350946485996246
epoch: 1500 cost: 0.1947513222694397
epoch: 1600 cost: 0.18668678402900696
epoch: 1700 cost: 0.1792379468679428
epoch: 1800 cost: 0.1723378747701645
epoch: 1900 cost: 0.16592955589294434
epoch: 2000 cost: 0.15996335446834564
epoch: 2100 cost: 0.1543959081172943
epoch: 2200 cost: 0.14918915927410126
epoch: 2300 cost: 0.14431045949459076
epoch: 2400 cost: 0.1397300362586975
epoch: 2500 cost: 0.13542188704013824
epoch: 2600 cost: 0.1313631236553192
e

In [45]:
prediction=model(x_train)
print(prediction)
for pred in prediction:
    print(pred.argmax().item())

tensor([[-11.4190,  -0.1089,  11.8240],
        [ -4.3004,   0.4548,   4.3716],
        [-18.3870,   8.3334,  11.4634],
        [-12.6072,   8.7538,   5.5110],
        [  0.9640,   3.5059,  -2.2739],
        [  4.2154,   7.4301,  -9.0254],
        [  7.0721,   4.7320,  -9.1733],
        [ 10.5025,   5.6715, -13.0728]], grad_fn=<AddmmBackward0>)
2
2
2
1
1
1
0
0


In [46]:
class SoftmaxModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [47]:
model=SoftmaxModel()
optimizer=optim.SGD(model.parameters(), lr=0.1)
epochs=10001

for epoch in range(epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch:',epoch, 'cost:',cost.item())

epoch: 0 cost: 2.637636423110962
epoch: 100 cost: 0.6479030251502991
epoch: 200 cost: 0.5646426677703857
epoch: 300 cost: 0.5110434293746948
epoch: 400 cost: 0.4672488868236542
epoch: 500 cost: 0.4282805621623993
epoch: 600 cost: 0.391924113035202
epoch: 700 cost: 0.35674208402633667
epoch: 800 cost: 0.32157716155052185
epoch: 900 cost: 0.28561723232269287
epoch: 1000 cost: 0.2508176863193512
epoch: 1100 cost: 0.23210185766220093
epoch: 1200 cost: 0.22086557745933533
epoch: 1300 cost: 0.21063703298568726
epoch: 1400 cost: 0.20127873122692108
epoch: 1500 cost: 0.19268494844436646
epoch: 1600 cost: 0.18476678431034088
epoch: 1700 cost: 0.17744912207126617
epoch: 1800 cost: 0.17066752910614014
epoch: 1900 cost: 0.16436627507209778
epoch: 2000 cost: 0.1584969311952591
epoch: 2100 cost: 0.1530178040266037
epoch: 2200 cost: 0.14789187908172607
epoch: 2300 cost: 0.14308682084083557
epoch: 2400 cost: 0.13857412338256836
epoch: 2500 cost: 0.13432839512825012
epoch: 2600 cost: 0.130327045917511


In [48]:
prediction=model(x_train)
print(prediction)
for pred in prediction:
    print(pred.argmax().item())

tensor([[-11.5040,  -0.2332,  11.5482],
        [ -4.5121,   0.3314,   4.2518],
        [-18.6585,   8.3969,  11.5301],
        [-13.0540,   8.7773,   5.5311],
        [  0.2068,   2.7515,  -3.0321],
        [  3.6675,   6.8847,  -8.6049],
        [  6.2559,   3.9120,  -9.5965],
        [  9.5304,   4.7042, -13.5660]], grad_fn=<AddmmBackward0>)
2
2
2
1
1
1
0
0


In [49]:
import sklearn.datasets as datasets
iris=datasets.load_iris()
# iris
# iris.data
iris.target
# iris.target_names

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
x_train=torch.FloatTensor(iris.data)
y_train=torch.LongTensor(iris.target)
print(x_train.size())
print(y_train.size())

torch.Size([150, 4])
torch.Size([150])


In [51]:
class SoftmaxModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [52]:
model=SoftmaxModel()
optimizer=optim.SGD(model.parameters(), lr=0.1)
epochs=10001

In [53]:
for epoch in range(epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch:',epoch, 'cost:',cost.item())

epoch: 0 cost: 2.214918851852417
epoch: 100 cost: 0.44505080580711365
epoch: 200 cost: 0.2598172426223755
epoch: 300 cost: 0.2164602130651474
epoch: 400 cost: 0.1892022341489792
epoch: 500 cost: 0.1703321486711502
epoch: 600 cost: 0.15643833577632904
epoch: 700 cost: 0.14574384689331055
epoch: 800 cost: 0.13723178207874298
epoch: 900 cost: 0.13027790188789368
epoch: 1000 cost: 0.124477319419384
epoch: 1100 cost: 0.11955566704273224
epoch: 1200 cost: 0.11532022058963776
epoch: 1300 cost: 0.11163146048784256
epoch: 1400 cost: 0.10838580876588821
epoch: 1500 cost: 0.10550463199615479
epoch: 1600 cost: 0.10292721539735794
epoch: 1700 cost: 0.10060573369264603
epoch: 1800 cost: 0.09850217401981354
epoch: 1900 cost: 0.09658568352460861
epoch: 2000 cost: 0.094831183552742
epoch: 2100 cost: 0.09321792423725128
epoch: 2200 cost: 0.09172862768173218
epoch: 2300 cost: 0.09034872055053711
epoch: 2400 cost: 0.08906595408916473
epoch: 2500 cost: 0.08786977827548981
epoch: 2600 cost: 0.08675126731395

In [63]:
prediction=model(x_train)
# print(prediction)

accuracys=[]
for i in range(len(prediction)):
    accuracys.append(y_train[i]==prediction[i].argmax())

print(len(accuracys), torch.FloatTensor(accuracys).sum())
print(torch.FloatTensor(accuracys).sum()/len(accuracys))

150 tensor(147.)
tensor(0.9800)
