In [7]:
import torch
import torch.optim as optim
import matplotlib.pyplot as plt

In [8]:
import pandas as pd
import numpy as np
df=pd.read_csv('data/data-01-test-score.csv')
data=np.array(df.values)
x_data = data[:, :3].reshape(-1,3)
t_data = data[:, :-1].reshape(-1,1)
print(x_data)
print(t_data)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[ 93]
 [ 88]
 [ 93]
 [ 89]
 [ 91]
 [ 90]
 [ 96]
 [ 98]
 [100]
 [ 73]
 [ 66]
 [ 70]
 [ 53]
 [ 46]
 [ 55]
 [ 69]
 [ 74]
 [ 77]
 [ 47]
 [ 56]
 [ 60]
 [ 87]
 [ 79]
 [ 90]
 [ 79]
 [ 70]
 [ 88]
 [ 69]
 [ 70]
 [ 73]
 [ 70]
 [ 65]
 [ 74]
 [ 93]
 [ 95]
 [ 91]
 [ 79]
 [ 80]
 [ 73]
 [ 70]
 [ 73]
 [ 78]
 [ 93]
 [ 89]
 [ 96]
 [ 78]
 [ 75]
 [ 68]
 [ 81]
 [ 90]
 [ 93]
 [ 88]
 [ 92]
 [ 86]
 [ 78]
 [ 83]
 [ 77]
 [ 82]
 [ 86]
 [ 90]
 [ 86]
 [ 82]
 [ 89]
 [ 78]
 [ 83]
 [ 85]
 [ 76]
 [ 83]
 [ 71]
 [ 96]
 [ 93]
 [ 95]]


In [9]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.62766657]
 [0.07668932]]
[0.80977145]


In [10]:
optimize = optim.SGD([w,b], lr = 0.01)
optimize

TypeError: optimizer can only optimize Tensors, but one of the params is ndarray

In [11]:
epochs=2001
for epoch in range(epochs):
    y=x_data*w+b
    cost=torch.mean((t_data-y)**2)
    optimize.zero_grad()
    cost.backward()
    optimize.step()

    if epoch % 100 == 0:
        print('epoch')

ValueError: operands could not be broadcast together with shapes (24,3) (2,1) 