pytorch를 cpu 버전으로 설치 (conda 설치 실패 시 이 방법으로 설치)
# ! pip install torch

In [1]:
import torch;

In [2]:
print(torch.tensor([[1,2],[3,4]]))
# print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
a=[[1,2,3,4], [10,20,30,40]]
t1=torch.tensor(a, dtype=torch.float64)
t1

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]], dtype=torch.float64)

In [4]:
ft=torch.FloatTensor(a); print(ft)
lt=torch.LongTensor(a); print(lt)
bt=torch.ByteTensor(a); print(bt)

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.uint8)


In [5]:
import numpy as np

In [6]:
x=np.array(a)
print(x, type(x))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


In [7]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.int32) <class 'torch.Tensor'>


In [8]:
x1=tx.numpy()
print(x1, type(x1))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


torch와 numpy는 쉽게 변환가능

In [9]:
# 파이토치 기본문법
print(tx)
ft=tx.float()
print(ft)
lt=ft.long()
print(lt)
it=lt.int()
print(it)
dt=it.byte()
print(dt)

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.uint8)


In [10]:
list=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
list

[[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18]]]

In [11]:
t1=torch.FloatTensor(list)
t1

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])

In [12]:
# torch tensor 크기
print(t1.size())
print(t1.shape)
print(t1.size(-1))
print(t1.shape[-1])

# 차원
print(t1.dim())
print(len(t1.size()))

torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
3
3
3
3


In [13]:
a = torch.FloatTensor([[1, 2],[3, 4]])
b = torch.FloatTensor([[2, 2],[3, 3]])

In [14]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])


In [15]:
print(a.mul(b))
print(a.sum()) # 합계
print(a.mean()) # 평균
print(a.sum(dim=0))
print(a.sum(dim=-1))
print(a.mean(dim=0))
print(a.mean(dim=-1))

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor(10.)
tensor(2.5000)
tensor([4., 6.])
tensor([3., 7.])
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [16]:
print(t1+10)
print(t1-1)

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[17., 18., 19.],
         [20., 21., 22.]],

        [[23., 24., 25.],
         [26., 27., 28.]]])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]]])


In [17]:
print(t1)
t0=torch.tensor([1,2,3]) # 1차원 크기 맞춰야 연산가능.
print(t1+t0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[ 2.,  4.,  6.],
         [ 5.,  7.,  9.]],

        [[ 8., 10., 12.],
         [11., 13., 15.]],

        [[14., 16., 18.],
         [17., 19., 21.]]])


In [18]:
t2=torch.tensor([[1,2,3],[4,5,6]]) # 1차원 크기에 맞춰야 연산가능
print(t1)
print(t2)
print(t1+t2)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[ 2.,  4.,  6.],
         [ 8., 10., 12.]],

        [[ 8., 10., 12.],
         [14., 16., 18.]],

        [[14., 16., 18.],
         [20., 22., 24.]]])


In [19]:
t1.size()

torch.Size([3, 2, 3])

In [20]:
# 형태변환
print(t1.view(-1))
print(t1.view(-1,3))
print(t1.view(3,-1))
print(t1.view(3,6))
print(t1.view(2,3,3))
print(t1.view(3,3,2))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.]]])


In [21]:
# 형태변환
print(t1.reshape(-1))
print(t1.reshape(-1,3))
print(t1.reshape(3,-1))
print(t1.reshape(3,6))
print(t1.reshape(2,3,3))
print(t1.reshape(3,3,2))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.]]])


In [22]:
print(t1.view(3,3,2,-1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]],

         [[ 5.],
          [ 6.]]],


        [[[ 7.],
          [ 8.]],

         [[ 9.],
          [10.]],

         [[11.],
          [12.]]],


        [[[13.],
          [14.]],

         [[15.],
          [16.]],

         [[17.],
          [18.]]]])


In [23]:
t10=t1.view(3,2,1,3)
print(t10.size())
t11=t10.squeeze() # 차원의 크기가 1인 차원 제거
print(t11.size())
t12=t11.unsqueeze(1) # 지정된 인덱스에 차원의 크기가 1인 차원 삽입
print(t12.size())

torch.Size([3, 2, 1, 3])
torch.Size([3, 2, 3])
torch.Size([3, 1, 2, 3])


In [24]:
print(t1)
print(t1[2,1])
print(t1[2,:,1])

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])
tensor([16., 17., 18.])
tensor([14., 17.])


In [25]:
x=torch.FloatTensor(10,4)
x

tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [26]:
splits = x.split(4, dim=0)
print(splits)

(tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]), tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]), tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]))


In [27]:
chunks = x.chunk(3, dim=0)
print(chunks)

(tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]), tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]), tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]))


In [28]:
print(t1)
indice=torch.LongTensor([1,2])
y=t1.index_select(dim=0, index=indice)
print(y)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])


In [29]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[11,12,13],[14,15,16],[17,18,19]])
print(x.size())
print(y.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [30]:
z=torch.cat([x,y], dim=0)
print(z)
z1=torch.cat([x,y], dim=1)
print(z1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])
tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.],
        [ 7.,  8.,  9., 17., 18., 19.]])


In [31]:
z11=torch.stack([x,y])
z11

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[11., 12., 13.],
         [14., 15., 16.],
         [17., 18., 19.]]])

In [32]:
x=torch.FloatTensor([[[1,2]],[[3,4]]])
print(x.size())
y=x.expand(2,3,2)
print(y)

torch.Size([2, 1, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [33]:
y=torch.cat([x]*3, dim=1)
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [34]:
x=torch.randperm(10)
print(x)
print(x.size())

tensor([3, 7, 8, 2, 0, 6, 1, 4, 9, 5])
torch.Size([10])


In [35]:
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())

tensor([[[18,  4, 20],
         [16,  6, 17],
         [10, 15, 26]],

        [[21,  1, 11],
         [ 7,  0, 23],
         [ 2,  8, 24]],

        [[13, 12,  5],
         [25, 19, 14],
         [ 9,  3, 22]]])
torch.Size([3, 3, 3])


In [36]:
# argmax(dim=n) (0:1차원, 1:2차원)
y1=x.argmax(dim=0)
print(y1)
y2=x.argmax(dim=1)
print(y2)
y3=x.argmax(dim=-1)
print(y3)

tensor([[1, 2, 0],
        [2, 2, 1],
        [0, 0, 0]])
tensor([[0, 2, 2],
        [0, 2, 2],
        [1, 1, 2]])
tensor([[2, 2, 2],
        [0, 2, 2],
        [0, 0, 2]])


In [37]:
#  가장 큰 k개 값과 index 반환
values, indices = torch.topk(x, k=2, dim=-1)
print(values)

tensor([[[20, 18],
         [17, 16],
         [26, 15]],

        [[21, 11],
         [23,  7],
         [24,  8]],

        [[13, 12],
         [25, 19],
         [22,  9]]])


In [38]:
x1=torch.FloatTensor([i for i in range(3**2)]).view(3,-1)
print(x1)
x2=torch.randperm(9).view(3,-1)
print(x2)

mask1=x1>4
print(mask1)
y1=x1.masked_fill(mask1, value=0) # mask 값이 True인 경우 0으로 출력
print(y1)

mask2=x2>4
print(mask2)
y2=x2.masked_fill(mask2, value=0)
print(y2)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[3, 6, 5],
        [1, 4, 2],
        [8, 0, 7]])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[0., 1., 2.],
        [3., 4., 0.],
        [0., 0., 0.]])
tensor([[False,  True,  True],
        [False, False, False],
        [ True, False,  True]])
tensor([[3, 0, 0],
        [1, 4, 2],
        [0, 0, 0]])


In [39]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [40]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
x.size()

torch.Size([2, 3])

In [41]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
