In [2]:
import numpy as np

In [3]:
def func1(x):
    return x**2
print(func1(3))

9


In [4]:
def func2(x):
    return 2*x**2+3*x+1
print(func2(3))

28


In [5]:
def numerical_derivative(f,x):
    delta_x=1e-4
    return(f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [6]:
result1=numerical_derivative(func1, 3)
result1

6.000000000012662

In [7]:
result2=numerical_derivative(func2, 2)
result2

11.00000000000989

In [8]:
def numerical_derivative2(f,x):
    delta_x = 1e-4
    grad=np.zeros_like(x)
    print('x:', x)
    print('grad:', grad)

    it=np.nditer(x, flags=['multi_index'])
    # flags : c_index(1차원 array일때), multi_index(2차원 이상일 때)
    # op_flags : 읽기/쓰기 옵션설정, default : readonly

    while not it.finished:
        idx=it.multi_index
        print('idx:', idx, 'x[idx]:', x[idx])
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx] =(fx1-fx2)/(2*delta_x)
        print('grad[idx]:', grad[idx])
        print('grad:', grad)

        x[idx]=tmp_val
        it.iternext()
    
    return grad

In [9]:
def func3(input):
    x=input[0]
    y=input[1]
    return (2*x + 3*x*y + np.power(y, 3))

In [10]:
numerical_derivative2(func3, np.array([1.0, 2.0]))

x: [1. 2.]
grad: [0. 0.]
idx: (0,) x[idx]: 1.0
grad[idx]: 7.999999999990237
grad: [8. 0.]
idx: (1,) x[idx]: 2.0
grad[idx]: 15.000000010019221
grad: [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [11]:
numerical_derivative2(func3, np.array([2.0, 1.0]))

x: [2. 1.]
grad: [0. 0.]
idx: (0,) x[idx]: 2.0
grad[idx]: 5.0000000000149925
grad: [5. 0.]
idx: (1,) x[idx]: 1.0
grad[idx]: 9.00000001000656
grad: [5.         9.00000001]


array([5.        , 9.00000001])

In [19]:
def func4(input):
    w=input[0][0]
    x=input[0][1]
    y=input[1][0]
    z=input[1][1]

    return(w*x + w*y*z + 3*w + z*np.power(y,2))

In [14]:
arr1=np.array([[1.0,2.0],[3.0,4.0]])
arr1

array([[1., 2.],
       [3., 4.]])

In [20]:
numerical_derivative2(func4, arr1)


x: [[1.0003 2.    ]
 [3.     4.    ]]
grad: [[0. 0.]
 [0. 0.]]
idx: (0, 0) x[idx]: 1.0003
grad[idx]: 16.999999999995907
grad: [[17.  0.]
 [ 0.  0.]]
idx: (0, 1) x[idx]: 2.0
grad[idx]: 1.0002999999869644
grad: [[17.      1.0003]
 [ 0.      0.    ]]
idx: (1, 0) x[idx]: 3.0
grad[idx]: 28.00120000006956
grad: [[17.      1.0003]
 [28.0012  0.    ]]
idx: (1, 1) x[idx]: 4.0
grad[idx]: 12.000900000010972
grad: [[17.      1.0003]
 [28.0012 12.0009]]


array([[17.    ,  1.0003],
       [28.0012, 12.0009]])