numpy 사용

In [5]:
# ! pip install numpy
import numpy as np
import pandas as pd

In [10]:
a=[1,2,3,'python',['a','b']]
a[3]

'python'

In [13]:
a=[1,2,3,'python']
b=[1,2,3,4,5]
arr_a = np.array(a)
arr_b = np.array(b)
print(arr_a)
print(arr_b)

['1' '2' '3' 'python']
[1 2 3 4 5]


In [15]:
print(arr_a[0:2])

['1' '2']


In [17]:
print(arr_a[::-1])

['python' '3' '2' '1']


In [21]:
list1=[[1,2,3],[10,20,30],[100,200,300]]
arr_1 = np.array(list1)
print(list1)
print(arr_1)
print(list1[0][0])
print(arr_1[0][0])
print(list1[1])
print(arr_1[1])

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
1
1
[10, 20, 30]
[10 20 30]


In [26]:
print(list1[:])
print(list1[:][1])
# arr_1[row, col]
print(arr_1[:,1])
print(arr_1[1,:2])

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]
[10, 20, 30]
[  2  20 200]
[10 20]


In [27]:
list1

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [31]:
print(arr_1+1)
print(arr_1-1)
print(arr_1*2)
print(arr_1/2)

[[  2   3   4]
 [ 11  21  31]
 [101 201 301]]
[[  0   1   2]
 [  9  19  29]
 [ 99 199 299]]
[[  2   4   6]
 [ 20  40  60]
 [200 400 600]]
[[  0.5   1.    1.5]
 [  5.   10.   15. ]
 [ 50.  100.  150. ]]


In [33]:
arr_2 = np.array([1,2,3])
arr_2

array([1, 2, 3])

In [35]:
print(arr_1+arr_2)

[[  2   4   6]
 [ 11  22  33]
 [101 202 303]]


In [36]:
arr_1.shape

(3, 3)

In [38]:
a=[1,2,3,4,5,6,7,8,9]
arr_a=np.array(a)
arr_a2=arr_a.reshape(3,3)
print(arr_a2)
arr_a1 = arr_a2.reshape(9)
print(arr_a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [42]:
arr1 = np.arange(1,13)
print(arr1)
arr2 = np.arange(1,13,1).reshape(3,4)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
